server:
  port: 8080
spring:
  application:
    name: "Franquicias"
  devtools:
    add-properties: false
  profiles:
    include: null
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
aws:
  dynamodb:
    endpoint: "http://localhost:4566"
  region: "us-east-1"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
