server:
  port: 8080
spring:
  application:
    name: "Franquicias"
  devtools:
    add-properties: false
  profiles:
    include: null
  docker:
    compose:
      lifecycle-management: start_only
      enabled: false
aws:
  dynamodb:
    endpoint: "${DYNAMODB_ENDPOINT:localhost:4566}"
  region: "${AWS_REGION:us-east-1}"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

#springdoc:
#  paths-to-match: /api/**
#  swagger-ui:
#    path: /swagger-ui.html
#  packages-to-scan: co.com.pruebatecnica.api
#logging:
#  level:
#    root: debug

